SELECT DEPARTMENT_ID,sum(SALARY) as sum,count(*) as
Number_of_Employees,avg(SALARY) as Average,min(salary) as Minimum , Max(SALARY) 
as Maximum FROM DBO.S_HREMPLOYEES sh
WHERE DEPARTMENT_ID IS NOT NULL GROUP BY DEPARTMENT_ID;

SELECT EMPLOYEE_ID, RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER
BY EMPLOYEE_ID ASC),DEPARTMENT_ID, FIRST_NAME ,LAST_NAME
FROM DBO.S_HREMPLOYEES sh ;

SELECT EMPLOYEE_ID, DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID 
ORDER BY EMPLOYEE_ID ASC),DEPARTMENT_ID, FIRST_NAME ,LAST_NAME
FROM DBO.S_HREMPLOYEES sh ;

select * from S_HRDEPARTMENTS as d inner join S_HREMPLOYEES as e on
e.DEPARTMENT_ID = d.DEPARTMENT_ID ;

select * from S_HRDEPARTMENTS as d left join S_HREMPLOYEES as e on
e.DEPARTMENT_ID = d.DEPARTMENT_ID ;

select * from S_HRDEPARTMENTS as d right join S_HREMPLOYEES as e on
e.DEPARTMENT_ID = d.DEPARTMENT_ID ;

select * from S_HRDEPARTMENTS as d full join S_HREMPLOYEES as e on
e.DEPARTMENT_ID = d.DEPARTMENT_ID ;